PREFIX hyfo: <http://hyfo.spatialai.org/v1/hyfo#>
PREFIX me_mgs: <http://sawgraph.spatialai.org/v1/me-mgs#>
PREFIX me_egad_data: <http://w3id.org/sawgraph/v1/me-egad-data#>
PREFIX me_egad: <http://w3id.org/sawgraph/v1/me-egad#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT * WHERE {
    ?s rdf:type me_egad:EGAD-SamplePoint ;
       me_egad:samplePointType me_egad_data:featureType.PWSW .
    ?o rdf:type me_mgs:MGS-Well .
    ?s hyfo:groundwaterConnected ?o .
    VALUES ?s {me_egad_data:samplePoint.95064}
}